Background@SETTINGS_PANEL:
	Logic: SettingsLogic
		HotkeyGroups:
			Game Commands:
				Template: TWO_COLUMN
				Types: OrderGenerator, World, Menu
			Viewport Commands:
				Template: TWO_COLUMN
				Types: Viewport
			Observer / Replay Commands:
				Template: TWO_COLUMN
				Types: Observer, Replay
			Unit Commands:
				Template: THREE_COLUMN
				Types: Unit
			Unit Stance Commands:
				Template: TWO_COLUMN
				Types: Stance
			Production Commands:
				Template: THREE_COLUMN
				Types: Production, ProductionSlot
			Support Power Commands:
				Template: THREE_COLUMN
				Types: SupportPower
			Music Commands:
				Template: TWO_COLUMN
				Types: Music
	X: (WINDOW_RIGHT - WIDTH) / 2
	Y: (WINDOW_BOTTOM -  HEIGHT) / 2
	Width: 600
	Height: 450
	Children:
		Label@SETTINGS_LABEL_TITLE:
			Y: 20
			Width: PARENT_RIGHT
			Height: 25
			Text: @SETTINGS-PANEL-SETTINGS-LABEL-TITLE-TEXT@
			Align: Center
			Font: Bold
		Button@RESET_BUTTON:
			X: 20
			Y: PARENT_BOTTOM - 45
			Width: 160
			Height: 25
			Text: @SETTINGS-PANEL-RESET-BUTTON-TEXT@
			Font: Bold
		Button@BACK_BUTTON:
			Key: escape
			X: PARENT_RIGHT - 180
			Y: PARENT_BOTTOM - 45
			Width: 160
			Height: 25
			Text: @SETTINGS-PANEL-BACK-BUTTON-TEXT@
			Font: Bold
		Container@TAB_CONTAINER:
			Y: 50
			Width: PARENT_RIGHT
			Height: 25
			Children:
				Button@DISPLAY_TAB:
					X: 115
					Width: 90
					Height: 25
					Text: @TAB-CONTAINER-DISPLAY-TAB-TEXT@
					Font: Bold
				Button@AUDIO_TAB:
					X: 205
					Width: 90
					Height: 25
					Text: @TAB-CONTAINER-AUDIO-TAB-TEXT@
					Font: Bold
				Button@INPUT_TAB:
					X: 295
					Width: 90
					Height: 25
					Text: @TAB-CONTAINER-INPUT-TAB-TEXT@
					Font: Bold
				Button@ADVANCED_TAB:
					X: 385
					Width: 90
					Height: 25
					Text: @TAB-CONTAINER-ADVANCED-TAB-TEXT@
					Font: Bold
		Container@DISPLAY_PANEL:
			X: 5
			Y: 50
			Width: PARENT_RIGHT - 10
			Height: PARENT_BOTTOM
			Children:
				Label@MODE_LABEL:
					X: 110
					Y: 39
					Width: 45
					Height: 25
					Align: Right
					Text: @DISPLAY-PANEL-MODE-LABEL-TEXT@
				DropDownButton@MODE_DROPDOWN:
					X: 160
					Y: 40
					Width: 170
					Height: 25
					Font: Regular
					Text: @DISPLAY-MODE-DROPDOWN-WINDOWED-TEXT@
				Container@WINDOW_RESOLUTION:
					X: 330
					Y: 40
					Children:
						Label@At:
							Text: @
							Font: Bold
							Y: 0 - 1
							Height: 25
							Width: 25
							Align: Center
						TextField@WINDOW_WIDTH:
							X: 25
							Width: 45
							Height: 25
							MaxLength: 5
							Type: Integer
						Label@X:
							Text: x
							Font: Bold
							X: 70
							Y: 0 - 1
							Height: 25
							Width: 15
							Align: Center
						TextField@WINDOW_HEIGHT:
							X: 85
							Width: 45
							Height: 25
							MaxLength: 5
							Type: Integer
				Checkbox@HARDWARECURSORS_CHECKBOX:
					X: 310
					Y: 75
					Width: 200
					Height: 20
					Font: Regular
					Text: @DISPLAY-PANEL-HARDWARECURSORS-CHECKBOX-TEXT@
				Label@VIDEO_DESC:
					Y: 93
					Width: PARENT_RIGHT
					Height: 25
					Font: Tiny
					Align: Center
					Text: @DISPLAY-PANEL-VIDEO-DESC-TEXT@
				Checkbox@FRAME_LIMIT_CHECKBOX:
					X: 15
					Y: 125
					Width: 200
					Height: 20
					Font: Regular
					Text: @DISPLAY-PANEL-FRAME-LIMIT-CHECKBOX-TEXT@
				Checkbox@PIXELDOUBLE_CHECKBOX:
					X: 310
					Y: 125
					Width: 200
					Height: 20
					Font: Regular
					Text: @DISPLAY-PANEL-PIXELDOUBLE-CHECKBOX-TEXT@
				Checkbox@CURSORDOUBLE_CHECKBOX:
					X: 340
					Y: 160
					Width: 200
					Height: 20
					Font: Regular
					Text: @DISPLAY-PANEL-CURSORDOUBLE-CHECKBOX-TEXT@
				Label@FRAME_LIMIT_DESC_A:
					X: 45
					Y: 157
					Width: 50
					Height: 25
					Text: @DISPLAY-PANEL-FRAME-LIMIT-DESC-A-TEXT@
					Align: Right
				TextField@FRAME_LIMIT_TEXTFIELD:
					X: 100
					Y: 158
					Width: 45
					Height: 25
					MaxLength: 3
					Type: Integer
				Label@FRAME_LIMIT_DESC_B:
					X: 150
					Y: 157
					Height: 25
					Text: @DISPLAY-PANEL-FRAME-LIMIT-DESC-B-TEXT@
				Checkbox@PLAYER_STANCE_COLORS_CHECKBOX:
					X: 310
					Y: 195
					Width: 200
					Height: 20
					Font: Regular
					Text: @DISPLAY-PANEL-PLAYER-STANCE-COLORS-CHECKBOX-TEXT@
				Label@PLAYER:
					Text: @DISPLAY-PANEL-PLAYER-TEXT@
					X: 15
					Y: 205
				TextField@PLAYERNAME:
					Text: Name
					X: 65
					Y: 195
					Width: 145
					Height: 25
					MaxLength: 16
				ColorPreviewManager@COLOR_MANAGER:
				DropDownButton@PLAYERCOLOR:
					X: 215
					Y: 195
					Width: 70
					Height: 25
					IgnoreChildMouseOver: true
					Children:
						ColorBlock@COLORBLOCK:
							X: 5
							Y: 6
							Width: PARENT_RIGHT - 35
							Height: PARENT_BOTTOM - 12
				Label@STATUS_BARS:
					X: 310
					Y: 275
					Text: @DISPLAY-PANEL-STATUS-BARS-TEXT@
				DropDownButton@STATUS_BAR_DROPDOWN:
					X: 400
					Y: 265
					Width: 170
					Height: 25
					Font: Regular
					Text: @DISPLAY-PANEL-STATUS-BAR-DROPDOWN-TEXT@
				Checkbox@DISPLAY_TARGET_LINES_CHECKBOX:
					X: 310
					Y: 230
					Width: 200
					Height: 20
					Font: Regular
					Text: @DISPLAY-PANEL-DISPLAY-TARGET-LINES-CHECKBOX-TEXT@
				Label@LOCALIZATION_TITLE:
					Y: 270
					Width: PARENT_RIGHT
					Font: Bold
					Text: @DISPLAY-PANEL-LOCALIZATION-TITLE-TEXT@
					Align: Center
					Visible: true
				Label@LANGUAGE_LABEL:
					X: 230 - WIDTH - 5
					Y: 289
					Width: 75
					Height: 25
					Align: Right
					Text: @DISPLAY-PANEL-LANGUAGE-LABEL-TEXT@
					Visible: true
				DropDownButton@LANGUAGE_DROPDOWNBUTTON:
					X: 230
					Y: 290
					Width: 200
					Height: 25
					Visible: true
				Label@LANGUAGE_DESC_A:
					Y: 310
					Width: PARENT_RIGHT
					Height: 25
					Font: Tiny
					Align: Center
					Text: @DISPLAY-PANEL-LANGUAGE-DESC-A-TEXT@
					Visible: true
				Label@LANGUAGE_DESC_B:
					Y: 325
					Width: PARENT_RIGHT
					Height: 25
					Font: Tiny
					Align: Center
					Text: @DISPLAY-PANEL-LANGUAGE-DESC-B-TEXT@
					Visible: true
		Container@AUDIO_PANEL:
			X: 5
			Y: 50
			Width: PARENT_RIGHT - 10
			Height: PARENT_BOTTOM
			Children:
				Label@SOUND_LABEL:
					X: PARENT_RIGHT - WIDTH - 270
					Y: 37
					Width: 95
					Height: 25
					Align: Right
					Text: @AUDIO-PANEL-SOUND-LABEL-TEXT@
				Slider@SOUND_VOLUME:
					X: PARENT_RIGHT - WIDTH - 15
					Y: 43
					Width: 250
					Height: 20
					Ticks: 5
				Checkbox@CASH_TICKS:
					X: 15
					Y: 40
					Width: 200
					Height: 20
					Font: Regular
					Text: @AUDIO-PANEL-CASH-TICKS-TEXT@
				Checkbox@MUTE_SOUND:
					X: 15
					Y: 70
					Width: 200
					Height: 20
					Font: Regular
					Text: @AUDIO-PANEL-MUTE-SOUND-TEXT@
				Label@MUSIC_LABEL:
					X: PARENT_RIGHT - WIDTH - 270
					Y: 67
					Width: 95
					Height: 25
					Align: Right
					Text: @AUDIO-PANEL-MUSIC-LABEL-TEXT@
				Slider@MUSIC_VOLUME:
					X: PARENT_RIGHT - WIDTH - 15
					Y: 73
					Width: 250
					Height: 20
					Ticks: 5
				Label@VIDEO_LABEL:
					X: PARENT_RIGHT - WIDTH - 270
					Y: 97
					Width: 95
					Height: 25
					Align: Right
					Text: @AUDIO-PANEL-VIDEO-LABEL-TEXT@
				Slider@VIDEO_VOLUME:
					X: PARENT_RIGHT - WIDTH - 15
					Y: 103
					Width: 250
					Height: 20
					Ticks: 5
				Label@AUDIO_DEVICE_LABEL:
					X: 190 - WIDTH - 5
					Y: 244
					Width: 75
					Height: 25
					Align: Right
					Text: @AUDIO-PANEL-AUDIO-DEVICE-LABEL-TEXT@
				DropDownButton@AUDIO_DEVICE:
					X: 190
					Y: 245
					Width: 300
					Height: 25
				Label@AUDIO_DEVICE_DESC:
					Y: 265
					Width: PARENT_RIGHT
					Height: 25
					Font: Tiny
					Align: Center
					Text: @AUDIO-PANEL-AUDIO-DEVICE-DESC-TEXT@
		Container@INPUT_PANEL:
			X: 5
			Y: 50
			Width: PARENT_RIGHT - 10
			Height: PARENT_BOTTOM
			Children:
				Checkbox@CLASSICORDERS_CHECKBOX:
					X: 15
					Y: 40
					Width: 250
					Height: 20
					Font: Regular
					Text: @INPUT-PANEL-CLASSICORDERS-CHECKBOX-TEXT@
				Label@MIDDLE_MOUSE_SCROLL_LABEL:
					X: PARENT_RIGHT - WIDTH - 120
					Y: 39
					Width: 160
					Height: 20
					Font: Regular
					Text: @INPUT-PANEL-MIDDLE-MOUSE-SCROLL-LABEL-TEXT@
					Align: Right
				DropDownButton@MIDDLE_MOUSE_SCROLL:
					X: PARENT_RIGHT - WIDTH - 15
					Y: 38
					Width: 100
					Height: 25
					Font: Regular
				Label@MIDDLE_MOUSE_SCROLL_LABEL:
					X: PARENT_RIGHT - WIDTH - 120
					Y: 69
					Width: 160
					Height: 20
					Font: Regular
					Text: @INPUT-PANEL-MIDDLE-MOUSE-SCROLL-LABEL-TEXTR@
					Align: Right
				DropDownButton@RIGHT_MOUSE_SCROLL:
					X: PARENT_RIGHT - WIDTH - 15
					Y: 68
					Width: 100
					Height: 25
					Font: Regular
				Label@ZOOM_MODIFIER_LABEL:
					X: PARENT_RIGHT - WIDTH - 120
					Y: 98
					Width: 160
					Height: 20
					Font: Regular
					Text: @INPUT-PANEL-ZOOM-MODIFIER-LABEL-TEXT@
					Align: Right
				DropDownButton@ZOOM_MODIFIER:
					X: PARENT_RIGHT - WIDTH - 15
					Y: 98
					Width: 100
					Height: 25
					Font: Regular
					Text: Alt
				Checkbox@EDGESCROLL_CHECKBOX:
					X: 15
					Y: 70
					Width: 130
					Height: 20
					Font: Regular
					Text: @INPUT-PANEL-EDGESCROLL-CHECKBOX-TEXT@
				Checkbox@ALLOW_ZOOM_CHECKBOX:
					X: 15
					Y: 100
					Width: 130
					Height: 20
					Font: Regular
					Text: @INPUT-PANEL-ALLOW-ZOOM-CHECKBOX-TEXT@
				Checkbox@LOCKMOUSE_CHECKBOX:
					X: 15
					Y: 130
					Width: 130
					Height: 20
					Font: Regular
					Text: @INPUT-PANEL-LOCKMOUSE-CHECKBOX-TEXT@
				Label@SCROLL_SPEED_LABEL:
					X: PARENT_RIGHT - WIDTH - 270
					Y: 127
					Width: 95
					Height: 25
					Text: @INPUT-PANEL-SCROLL-SPEED-LABEL-TEXT@
					Align: Right
				Slider@SCROLLSPEED_SLIDER:
					X: PARENT_RIGHT - WIDTH - 170
					Y: 133
					Width: 100
					Height: 20
					Ticks: 5
					MinimumValue: 10
					MaximumValue: 50
				Label@UI_SCROLL_SPEED_LABEL:
					X: PARENT_RIGHT - WIDTH - 106
					Y: 127
					Width: 95
					Height: 25
					Text: @INPUT-PANEL-UI-SCROLL-SPEED-LABEL-TEXT@
					Align: Right
				Slider@UI_SCROLLSPEED_SLIDER:
					X: PARENT_RIGHT - WIDTH - 6
					Y: 133
					Width: 100
					Height: 20
					Ticks: 5
					MinimumValue: 1
					MaximumValue: 100
				Label@HOTKEYS_TITLE:
					Y: 165
					Width: PARENT_RIGHT
					Font: Bold
					Text: @INPUT-PANEL-HOTKEYS-TITLE-TEXT@
					Align: Center
				ScrollPanel@HOTKEY_LIST:
					X: 15
					Y: 185
					Width: 560
					TopBottomSpacing: 4
					ItemSpacing: 4
					Height: 160
					Children:
						ScrollItem@HEADER:
							BaseName: scrollheader
							Width: 528
							Height: 13
							Visible: false
							Children:
								Label@LABEL:
									Font: TinyBold
									Width: PARENT_RIGHT
									Height: 10
									Align: Center
								ScrollItem@HEADER:
									Width: 528
									Height: 13
									Visible: false
									Children:
										Label@LABEL:
											Font: TinyBold
											Width: PARENT_RIGHT
											Height: 10
											Align: Center
								Container@TEMPLATES:
									Children:
										Container@TWO_COLUMN:
											Width: 262
											Height: 25
											Visible: false
											Children:
												Label@FUNCTION:
													Y: 0 - 1
													Width: PARENT_RIGHT - 85
													Height: 25
													Align: Right
												HotkeyEntry@HOTKEY:
													X: PARENT_RIGHT - WIDTH
													Width: 80
													Height: 25
										Container@THREE_COLUMN:
											Width: 173
											Height: 25
											Visible: false
											Children:
												Label@FUNCTION:
													Y: 0 - 1
													Width: PARENT_RIGHT - 84
													Height: 25
													Align: Right
												HotkeyEntry@HOTKEY:
													X: PARENT_RIGHT - WIDTH + 1
													Width: 80
													Height: 25
		Container@ADVANCED_PANEL:
			X: 5
			Y: 50
			Width: PARENT_RIGHT - 10
			Height: PARENT_BOTTOM
			Children:
				Checkbox@NAT_DISCOVERY:
					X: 15
					Y: 40
					Width: 200
					Height: 20
					Font: Regular
					Text: @ADVANCED-PANEL-NAT-DISCOVERY-TEXT@
				Checkbox@PERFTEXT_CHECKBOX:
					X: 15
					Y: 70
					Width: 300
					Height: 20
					Font: Regular
					Text: @ADVANCED-PANEL-PERFTEXT-CHECKBOX-TEXT@
				Checkbox@PERFGRAPH_CHECKBOX:
					X: 15
					Y: 100
					Width: 300
					Height: 20
					Font: Regular
					Text: @ADVANCED-PANEL-PERFGRAPH-CHECKBOX-TEXT@
				Checkbox@FETCH_NEWS_CHECKBOX:
					X: 310
					Y: 40
					Width: 300
					Height: 20
					Font: Regular
					Text: @ADVANCED-PANEL-FETCH-NEWS-CHECKBOX-TEXT@
				Checkbox@CHECK_VERSION_CHECKBOX:
					X: 310
					Y: 70
					Width: 300
					Height: 20
					Font: Regular
					Text: @ADVANCED-PANEL-CHECK-VERSION-CHECKBOX-TEXT@
				Checkbox@SENDSYSINFO_CHECKBOX:
					X: 310
					Y: 100
					Width: 300
					Height: 20
					Font: Regular
					Text: @ADVANCED-PANEL-SENDSYSINFO-CHECKBOX-TEXT@
				Label@SENDSYSINFO_DESC:
					X: 310
					Y: 115
					Width: 250
					Height: 30
					Font: Tiny
					WordWrap: True
					Text: @ADVANCED-PANEL-SENDSYSINFO-DESC-TEXT@
				Label@DEBUG_TITLE:
					Y: 200
					Width: PARENT_RIGHT
					Font: Bold
					Text: @ADVANCED-PANEL-DEBUG-TITLE-TEXT@
					Align: Center
				Checkbox@BOTDEBUG_CHECKBOX:
					X: 15
					Y: 220
					Width: 300
					Height: 20
					Font: Regular
					Text: @ADVANCED-PANEL-BOTDEBUG-CHECKBOX-TEXT@
				Checkbox@CHECKUNSYNCED_CHECKBOX:
					X: 15
					Y: 250
					Width: 300
					Height: 20
					Font: Regular
					Text: @ADVANCED-PANEL-CHECKUNSYNCED-CHECKBOX-TEXT@
				Checkbox@LUADEBUG_CHECKBOX:
					X: 310
					Y: 220
					Width: 300
					Height: 20
					Font: Regular
					Text: @ADVANCED-PANEL-LUADEBUG-CHECKBOX-TEXT@
				Checkbox@REPLAY_COMMANDS_CHECKBOX:
					X: 310
					Y: 250
					Width: 300
					Height: 20
					Font: Regular
					Text: @ADVANCED-PANEL-REPLAY-COMMANDS-CHECKBOX-TEXT@
